site_name: NOMAD Workflows Documentation
site_description: |
  NOMAD custom and automatic workflow documentation.
site_author: FAIRmat consortium
nav:
  - Home: index.md
  - Uploading and publishing data: 
    - Introduction: uploading_and_publishing_data/intro.md
    - Creating an account: uploading_and_publishing_data/01_create_account.md
  - Custom schemas for new features: 
    - Introduction: custom_schemas_for_new_features/intro.md
  - Writing a parser plugin: 
    - Introduction: writing_a_parser_plugin/intro.md
  - Normalizing the parsed metadata: 
    - Introduction: normalizing_the_parsed_metadata/intro.md
  - Querying and performing Data Science: 
    - Introduction: querying_and_performing_Data_Science/intro.md
  - Visualizing properties in the entry page: 
    - Introduction: visualizing_properties_in_the_entry_page/intro.md
  - Defining filters for searches: 
    - Introduction: defining_filters_for_searches/intro.md
  - Current features: 
    - Introduction: current_features/intro.md
theme:
  name: material
  palette:
    primary: '#2A4CDF'
    accent: '#008A67'
  font:
    text: 'Titillium Web'
  logo: assets/nomad-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: True
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css
